### ISSUE TITLE
express use less middleware 

### ISSUE THREAD

**Issue by boneyao** [emberfeather/less.js-middleware#105]
/root/node_modules/express/node_modules/etag/index.js:55
    throw new TypeError('argument entity must be string or Buffer')
          ^
TypeError: argument entity must be string or Buffer
    at etag (/root/node_modules/express/node_modules/etag/index.js:55:11)
    at SendStream.setHeader (/root/node_modules/express/node_modules/send/index.js:728:15)
    at SendStream.send (/root/node_modules/express/node_modules/send/index.js:500:8)
    at onstat (/root/node_modules/express/node_modules/send/index.js:588:10)
    at Object.oncomplete (fs.js:97:15)
Program node app.js exited with code 1

use "graceful-fs " fs.stat result is not instanceOf fs.Stats

**Comment by havenchyk** [comment]
Is this issue still actual?
